### ISSUE TITLE
 new pages in "About" not displaying

### ISSUE THREAD

**Issue by millertg** [VandyVRC/srophe-eXist-app#226]
@wsalesky @shubenda Yuh-Fen added a link to the new 2022 page on the About page, but, although we copied the old page and can see everything on Github, it doesn't display on the AS site. I looked at the page carefully and didn't see any obvious errors. Winona, can you tell us what we are doing wrong? Or could this be a webhook issue?
![Screen Shot 2022-06-21 at 3 41 29 PM](https://user-images.githubusercontent.com/25234059/174894159-701d48c4-1bfe-4676-8077-7916e70ec1f3.png)

**Comment by wsalesky** [comment]
@millertg @shubenda It did not load because there is an unclosed li tag. Here is the error from the webhooks: 

   ` <message>Failed to update resource /db/apps/tcadrt/contributorsATTCAT2022.html: java:org.xmldb.api.base.XMLDBException: The XML parser reported a problem: fatal error at (70,23) : The element type "li" must be terminated by the matching end-tag "&lt;/li&gt;". XMLDB reported an exception while storing document: The XML parser reported a problem: fatal error at (70,23) : The element type "li" must be terminated by the matching end-tag "&lt;/li&gt;".</message>
`

Here is the unclosed tag: https://github.com/VandyVRC/srophe-eXist-app/blob/master/contributorsATTCAT2022.html#L25

Once it is closed, be sure to test if the document is well formed in Oxygen before saving to github. eXist-db can not store poorly formed XML.

**Comment by shubenda** [comment]
Thank you, Winona!
I fixed.
So many pairs of eyes looked at the code, none of us saw the unclosed tag.

Will view in oxygen in the future.

Yuh-Fen

**Comment by wsalesky** [comment]
@shubenda Great! It is always hard to catch these little bugs, that is why Oxygen is so useful.
